-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgnmb7/yXXL+z0DVJn
NWG+UQN+Kr9+wOlMqWxGXdG2juqgCgYIKoZIzj0DAQehRANCAARGFUBq7EWNCHC9
6S+OC2oZGjbELAwKKc7wq9s1TIE6/Gc/ZieoZ38Dnm6vvmIQRudewEwjYp1PQ252
ACmEH6Bm
-----END PRIVATE KEY-----